services:
  configsvr:
    image: mongo:7
    container_name: lab15_configsvr
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - configsvr_data:/data/db

  shard1:
    image: mongo:7
    container_name: lab15_shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo:7
    container_name: lab15_shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020 --bind_ip_all
    ports:
      - "27020:27020"
    volumes:
      - shard2_data:/data/db

  mongos:
    image: mongo:7
    container_name: lab15_mongos
    command: mongos --configdb configReplSet/configsvr:27019 --bind_ip_all --port 27017
    #punto de conexion del cluster: mongodb://localhost:28017
    ports:
      - "28017:27017"
    depends_on:
      - configsvr
      - shard1
      - shard2

volumes:
  configsvr_data:
  shard1_data:
  shard2_data:
